import { MaximedShell, RoleAccess } from "@/components/MaximedShell";
import { NalediPanel } from "@/components/NalediPanel";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, ChevronRight, FileText, GraduationCap, PlayCircle, ShieldCheck } from "lucide-react";
import { useRoute, useLocation } from "wouter";

function CourseContent({ courseId }: { courseId: number }) {
  const [, setLocation] = useLocation();
  const course = trpc.learning.course.useQuery({ courseId });
  const complete = trpc.learning.completeModule.useMutation({ onSuccess: () => course.refetch() });
  if (course.isLoading) return <MaximedShell space="learner" eyebrow="Course workspace" title="Loading course" description="Preparing your learning workspace."><div className="h-52 animate-pulse rounded-2xl bg-slate-200" /></MaximedShell>;
  if (!course.data) return <MaximedShell space="learner" eyebrow="Course workspace" title="Course unavailable" description="This course may not be available to your account yet."><button onClick={() => setLocation("/learn")} className="inline-flex items-center gap-2 rounded-xl bg-[#093B88] px-4 py-3 text-sm font-extrabold text-white"><ArrowLeft className="h-4 w-4" />Return to learning</button></MaximedShell>;
  const { course: details, modules, enrollment } = course.data;
  const completedModules = modules.filter(module => module.completedAt).length;
  const progress = enrollment?.progressPercent ?? (modules.length ? Math.round((completedModules / modules.length) * 100) : 0);
  return <MaximedShell space="learner" eyebrow="Course workspace" title={details.title} description={details.summary || "Complete each learning step, then submit your required assessment."}>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
      <button onClick={() => setLocation("/learn")} className="inline-flex items-center gap-2 text-sm font-extrabold text-[#093B88]"><ArrowLeft className="h-4 w-4" />Back to my learning</button>
      <NalediPanel courseId={courseId} />
    </div>
    <section className="rounded-2xl bg-[#093B88] p-5 text-white sm:p-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="section-kicker text-white/60">Learning progress</p><p className="mt-2 text-3xl font-extrabold">{progress}% complete</p></div><div className="rounded-xl bg-white/12 px-3 py-2 text-sm font-bold">{completedModules} of {modules.length} steps</div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#E20000]" style={{ width: `${progress}%` }} /></div></section><section className="mt-7 grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 app-surface"><p className="section-kicker text-[#DA0000]">Course details</p><p className="mt-3 text-sm leading-6 text-slate-600">Estimated completion time: <strong className="text-slate-800">{details.estimatedMinutes} minutes</strong></p><div className="mt-6 space-y-3"><div className="flex gap-3 text-sm text-slate-600"><ShieldCheck className="h-5 w-5 shrink-0 text-[#093B88]" /><span>Required items and acknowledgements are recorded to your profile.</span></div><div className="flex gap-3 text-sm text-slate-600"><GraduationCap className="h-5 w-5 shrink-0 text-[#093B88]" /><span>Assessment outcomes are available to authorised teaching staff.</span></div></div></div><div className="space-y-3">{modules.map((module, index) => { const icon = module.moduleType === "video" ? <PlayCircle /> : module.moduleType === "quiz" ? <GraduationCap /> : <FileText />; return <article key={module.id} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4 app-surface"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${module.completedAt ? "bg-emerald-50 text-emerald-700" : "bg-[#EAF1FB] text-[#093B88]"}`}>{module.completedAt ? <CheckCircle2 className="h-5 w-5" /> : <span className="text-sm font-extrabold">{index + 1}</span>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold text-slate-900">{module.title}</h3><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-extrabold uppercase tracking-wide text-slate-500">{module.moduleType}</span></div><p className="mt-1 text-sm leading-6 text-slate-600">{module.body || `${module.estimatedMinutes} minute learning step`}</p>{!module.completedAt ? <button disabled={complete.isPending} onClick={() => complete.mutate({ moduleId: module.id, acknowledgement: module.moduleType === "acknowledgement" })} className="mt-3 inline-flex items-center gap-1 text-sm font-extrabold text-[#093B88]">Mark complete <ChevronRight className="h-4 w-4" /></button> : <p className="mt-3 text-xs font-extrabold text-emerald-700">Completed</p>}</div><span className="hidden h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-50 text-slate-400 sm:grid">{icon}</span></article>; })}</div></section>
  </MaximedShell>;
}

export default function CourseWorkspace() { const [, params] = useRoute("/course/:id"); const courseId = Number(params?.id ?? 0); return <RoleAccess allowed={["learner", "trainer", "admin"]} title="Maximed course workspace">{courseId > 0 ? <CourseContent courseId={courseId} /> : <div />}</RoleAccess>; }
