import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ArrowRight, BadgeCheck, BookOpen, ChartNoAxesCombined, ClipboardCheck, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

const pathways = [
  ["01", "Product Training", "Build practical confidence across the Maximed range."],
  ["02", "Self Development", "Strengthen the habits that support everyday performance."],
  ["03", "Business Training 101", "Learn the foundations behind a consistent customer experience."],
  ["04", "KPIs", "Understand the measures that guide focused branch performance."],
  ["05", "Regulatory Training", "Keep required knowledge current, documented, and complete."],
];

export default function Home() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const primaryAction = () => user ? setLocation(user.role === "learner" ? "/learn" : "/training") : startLogin();

  return (
    <div className="min-h-screen overflow-hidden bg-[#F7F9FC] text-slate-950">
      <header className="border-b border-slate-200 bg-white"><div className="container flex h-16 items-center justify-between"><span className="maximed-wordmark text-xl text-[#093B88]">MAXIMED<sup>+</sup></span><button onClick={primaryAction} className="rounded-lg bg-[#093B88] px-4 py-2.5 text-sm font-extrabold text-white transition-transform duration-150 active:scale-[0.98]">{loading ? "Loading…" : user ? "Open learning" : "Sign in"}</button></div></header>
      <main>
        <section className="container grid gap-10 py-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-24">
          <div className="max-w-2xl"><p className="section-kicker text-[#DA0000]">Maximed staff learning</p><h1 className="mt-4 text-5xl font-extrabold tracking-[-0.055em] text-[#093B88] sm:text-6xl lg:text-7xl">Train with clarity.<br /><span className="text-slate-950">Perform with confidence.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">A focused learning platform for Maximed teams—bringing product knowledge, everyday capability, business fundamentals, and compliance together.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={primaryAction} className="inline-flex items-center gap-2 rounded-xl bg-[#093B88] px-5 py-3.5 text-sm font-extrabold text-white transition-transform duration-150 active:scale-[0.98]">{user ? "Continue learning" : "Sign in with email"}<ArrowRight className="h-4 w-4" /></button><button onClick={() => document.getElementById("pathways")?.scrollIntoView({ behavior: "smooth" })} className="rounded-xl border border-slate-300 bg-white px-5 py-3.5 text-sm font-extrabold text-slate-700">Explore pathways</button></div><p className="mt-5 text-xs font-semibold text-slate-500">Access is provided to Maximed staff by invitation. Learning records are tied to your profile.</p></div>
          <div className="relative mx-auto w-full max-w-xl"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-[#DA0000]/10 blur-2xl" /><div className="relative rounded-[2rem] bg-[#093B88] p-5 text-white shadow-2xl shadow-[#093B88]/20 sm:p-7"><div className="flex items-start justify-between"><div><p className="section-kicker text-white/60">Your learning space</p><h2 className="mt-2 text-2xl font-extrabold">Progress that stays useful</h2></div><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/15"><BookOpen className="h-5 w-5" /></div></div><div className="mt-7 rounded-2xl bg-white p-4 text-slate-900"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold">Learn at your pace</p><p className="mt-1 text-xs text-slate-500">Pick up where you left off.</p></div><span className="rounded-full bg-[#EAF1FB] px-2.5 py-1 text-xs font-extrabold text-[#093B88]">Personal profile</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[68%] rounded-full bg-[#DA0000]" /></div><div className="mt-3 flex justify-between text-xs font-bold text-slate-500"><span>Learning journey</span><span>Progress recorded</span></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/15 bg-white/8 p-4"><ShieldCheck className="h-5 w-5 text-[#D7E8FF]" /><p className="mt-5 text-sm font-extrabold">Built for compliance</p><p className="mt-1 text-xs leading-5 text-white/65">Required learning and acknowledgements are clearly tracked.</p></div><div className="rounded-2xl border border-white/15 bg-white/8 p-4"><ChartNoAxesCombined className="h-5 w-5 text-[#D7E8FF]" /><p className="mt-5 text-sm font-extrabold">Visible outcomes</p><p className="mt-1 text-xs leading-5 text-white/65">Teaching teams can identify completion and results.</p></div></div></div></div>
        </section>
        <section id="pathways" className="border-y border-slate-200 bg-white"><div className="container py-16"><div className="flex max-w-2xl flex-col gap-3"><p className="section-kicker text-[#DA0000]">Continuous learning</p><h2 className="text-3xl font-extrabold tracking-tight text-slate-950">Five pathways, one shared standard.</h2><p className="text-sm leading-6 text-slate-600">Courses can bring together written guidance, video, documents, slides, acknowledgements, and controlled assessments.</p></div><div className="mt-9 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{pathways.map(([number, title, description]) => <article key={number} className="rounded-2xl border border-slate-200 bg-[#FBFCFE] p-5 transition-transform duration-200 hover:-translate-y-1"><span className="brand-font text-xs font-bold text-[#DA0000]">{number}</span><h3 className="mt-8 text-base font-extrabold text-[#093B88]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></div></section>
        <section className="container grid gap-4 py-16 md:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6 app-surface"><BadgeCheck className="h-6 w-6 text-[#DA0000]" /><h3 className="mt-6 font-extrabold">Clear learning standards</h3><p className="mt-2 text-sm leading-6 text-slate-600">Passing marks and attempt limits bring consistency to assessed training.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6 app-surface"><ClipboardCheck className="h-6 w-6 text-[#093B88]" /><h3 className="mt-6 font-extrabold">Simple for learners</h3><p className="mt-2 text-sm leading-6 text-slate-600">A quiet, focused experience designed for work on mobile and desktop.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6 app-surface"><ChartNoAxesCombined className="h-6 w-6 text-[#093B88]" /><h3 className="mt-6 font-extrabold">Meaningful visibility</h3><p className="mt-2 text-sm leading-6 text-slate-600">Teaching staff can monitor participation, completion, and assessment performance.</p></article></section>
      </main>
      <footer className="border-t border-slate-200 bg-white"><div className="container flex flex-col gap-3 py-7 text-xs font-semibold text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>© Maximed. Internal staff learning.</span><span>Secure profile-based learning records.</span></div></footer>
    </div>
  );
}
