import { MaximedShell, RoleAccess } from "@/components/MaximedShell";
import { trpc } from "@/lib/trpc";
import { BarChart3, CheckCircle2, ClipboardList, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

type FilterKey = "branch" | "region" | "jobRole" | "managerName" | "productTeam";

function TrainerContent() {
  const [filters, setFilters] = useState<Record<FilterKey, string>>({ branch: "", region: "", jobRole: "", managerName: "", productTeam: "" });
  const activeFilters = useMemo(() => Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) as Partial<Record<FilterKey, string>>, [filters]);
  const reporting = trpc.staff.overview.useQuery(activeFilters);
  const metrics = reporting.data?.metrics ?? { learners: 0, publishedCourses: 0, assigned: 0, completed: 0, completionRate: 0, averageScore: 0 };
  const dimensions = reporting.data?.dimensions ?? { branches: [], regions: [], jobRoles: [], managers: [], productTeams: [] };
  const learners = reporting.data?.learners ?? [];
  const dimensionEntries: Array<{ key: FilterKey; label: string; values: string[] }> = [
    { key: "branch", label: "Branch", values: dimensions.branches }, { key: "region", label: "Region", values: dimensions.regions }, { key: "jobRole", label: "Job role", values: dimensions.jobRoles }, { key: "managerName", label: "Manager", values: dimensions.managers }, { key: "productTeam", label: "Product team", values: dimensions.productTeams },
  ];

  return <MaximedShell space="trainer" eyebrow="Teaching staff" title="Training performance, in context." description="Review learner participation, course completion, and assessment results across the Maximed organisation.">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Learners" value={metrics.learners} description="Within current filters" icon={<UsersRound className="h-5 w-5" />} /><Metric label="Live courses" value={metrics.publishedCourses ?? 0} description="Published to staff" icon={<ClipboardList className="h-5 w-5" />} /><Metric label="Assigned items" value={metrics.assigned} description="Learning records" icon={<ClipboardList className="h-5 w-5" />} /><Metric label="Completion rate" value={`${metrics.completionRate}%`} description={`${metrics.completed} completed`} icon={<CheckCircle2 className="h-5 w-5" />} /><Metric label="Average score" value={`${metrics.averageScore}%`} description="Assessment attempts" icon={<BarChart3 className="h-5 w-5" />} /></section>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 app-surface"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="section-kicker text-[#DA0000]">Report filters</p><h2 className="mt-1 font-extrabold">Understand results by team</h2></div><button onClick={() => setFilters({ branch: "", region: "", jobRole: "", managerName: "", productTeam: "" })} className="text-sm font-extrabold text-[#093B88]">Clear filters</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{dimensionEntries.map(({ key, label, values }) => <label key={key} className="text-xs font-bold text-slate-500"><span>{label}</span><select value={filters[key]} onChange={event => setFilters(current => ({ ...current, [key]: event.target.value }))} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700"><option value="">All {label.toLowerCase()}s</option>{values.map(value => <option key={value} value={value}>{value}</option>)}</select></label>)}</div></section>
    <section id="learners" className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white app-surface"><div className="flex items-center justify-between p-5"><div><p className="section-kicker text-[#DA0000]">Learner results</p><h2 className="mt-1 font-extrabold">Organisation-wide learner view</h2></div><span className="text-xs font-bold text-slate-500">{learners.length} shown</span></div>{learners.length ? <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead className="border-y border-slate-100 bg-slate-50 text-[11px] font-extrabold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Learner</th><th className="px-4 py-3">Team</th><th className="px-4 py-3">Course progress</th><th className="px-4 py-3">Results</th><th className="px-4 py-3">Last activity</th></tr></thead><tbody>{learners.map(learner => <tr key={learner.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="text-sm font-extrabold text-slate-900">{learner.name || "Unnamed learner"}</p><p className="mt-1 text-xs text-slate-500">{learner.email || "No email recorded"}</p></td><td className="px-4 py-4 text-sm text-slate-600">{[learner.branch, learner.region, learner.productTeam].filter(Boolean).join(" · ") || "Not yet set"}</td><td className="px-4 py-4"><p className="text-sm font-bold text-slate-700">{learner.completed}/{learner.enrolled} complete</p>{learner.courses.length ? <div className="mt-2 space-y-1">{learner.courses.map(course => <p key={`${course.courseId}-${course.courseTitle}`} className="max-w-52 truncate text-xs text-slate-500">{course.courseTitle} · {course.progressPercent}%</p>)}</div> : null}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-extrabold ${learner.averageScore === null ? "bg-slate-100 text-slate-500" : learner.averageScore >= 80 ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-[#DA0000]"}`}>{learner.averageScore === null ? "No attempt" : `${learner.averageScore}% average`}</span></td><td className="px-4 py-4 text-sm text-slate-500">{learner.lastActivity ? new Date(learner.lastActivity).toLocaleDateString() : "No activity"}</td></tr>)}</tbody></table></div> : <EmptyResults />}</section>
  </MaximedShell>;
}

function Metric({ label, value, description, icon }: { label: string; value: string | number; description: string; icon: React.ReactNode }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 app-surface"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EAF1FB] text-[#093B88]">{icon}</span></div><p className="metric-value mt-6 text-3xl font-extrabold text-slate-950">{value}</p><p className="mt-1 text-sm font-extrabold text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-500">{description}</p></article>; }
function EmptyResults() { return <div className="px-5 py-12 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-[#EAF1FB] text-[#093B88]"><UsersRound className="h-5 w-5" /></div><h3 className="mt-4 font-extrabold">Results will appear here</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">As Maximed users are added and assigned learning, this view will report participation, completion, and assessment performance.</p></div>; }
export default function TrainerDashboard() { return <RoleAccess allowed={["trainer", "admin"]} title="Maximed training dashboard"><TrainerContent /></RoleAccess>; }
